export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
export const PAYMENT_METHODS = Symbol('PAYMENT_METHODS');
export const CHEQUE_SUBMISSION_REPOSITORY = Symbol(
  'CHEQUE_SUBMISSION_REPOSITORY',
);
export const BANK_ACCOUNT_VALIDATION_REPOSITORY = Symbol(
  'BANK_ACCOUNT_VALIDATION_REPOSITORY',
);
export const BANK_ACCOUNT_INQUIRY = Symbol('BANK_ACCOUNT_INQUIRY');
