enum ErrorCode {
  INTERNAL = 'INTERNAL',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION = 'VALIDATION',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_OTP = 'INVALID_OTP',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_RATE_LIMITED = 'OTP_RATE_LIMITED',
  PHONE_ALREADY_REGISTERED = 'PHONE_ALREADY_REGISTERED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  SELLER_ALREADY_EXISTS = 'SELLER_ALREADY_EXISTS',
  SELLER_NOT_ACTIVE = 'SELLER_NOT_ACTIVE',
  SELLER_NOT_FOUND = 'SELLER_NOT_FOUND',
  SELLER_PROFILE_INCOMPLETE = 'SELLER_PROFILE_INCOMPLETE',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
}

export default ErrorCode;
