export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PENDING_SIGNUP_REPOSITORY = Symbol('PENDING_SIGNUP_REPOSITORY');
export const SELLER_SUMMARY_QUERY = Symbol('SELLER_SUMMARY_QUERY');
export const CREATE_PENDING_SELLER = Symbol('CREATE_PENDING_SELLER');
