export const SELLER_REPOSITORY = Symbol('SELLER_REPOSITORY');
export const SELLER_WAREHOUSE_REPOSITORY = Symbol(
  'SELLER_WAREHOUSE_REPOSITORY',
);
export const RETAIL_SELLER_PROFILE_REPOSITORY = Symbol(
  'RETAIL_SELLER_PROFILE_REPOSITORY',
);
