enum Role {
  RETAIL_BUYER = 'RETAIL_BUYER',
  WHOLESALE_BUYER = 'WHOLESALE_BUYER',
  RETAIL_SELLER = 'RETAIL_SELLER',
  WHOLESALE_SELLER = 'WHOLESALE_SELLER',
  ADMIN = 'ADMIN',
}

export default Role;
