enum OrderStatus {
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  PREPARING = 'PREPARING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export default OrderStatus;
